# Generated by Django 3.0.3 on 2022-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetailinfo',
            name='file_url',
            field=models.FileField(upload_to='directory/'),
        ),
    ]
